### ISSUE TITLE
(Feature Request) External audio input support

### ISSUE THREAD

**Issue by bierviltje** [moneriomaa/openear#1]
I (and probably many others) would like to see external audio input (virtual audio cable) support in a future update.

Currently I can only use my rtl-sdr dongles with the Tetra Demodulator plugin for SDR#. Because my dongles aren't directly plugged into my computer (I use remote rtl_tcp servers) I'm unable to use your software.

I also recently purchased a SDRplay RSP1A which doesn't work with SDR#, so I'm unable to decode Tetra. (I can do all other modes such as DMR, P25 etc with linking the audio output to DSDplus audio input).

**Comment by moneriomaa** [comment]
Hello
This request has two parts
The simplest part is to add the reading data from the audio device where this is applicable
The second part of the output is for software such as the demodulator of this protocol is pi/4DQPSK the input data must be raw(I/Q) and may be slightly different with the standard audio rate for specified demodulator that i used
I'm trying to find a better demodulator that has a lower error rate for improve performance for weaker signal. After finding this demodulator I will definitely add a feature that is not too far off, maybe in the 3 month period.
