### ISSUE TITLE
i need OpenEar source code

### ISSUE THREAD

**Issue by BenjiWiebe** [moneriomaa/openear#10]
According to the GPL, if you link a library that is GPL, the program itself must also be GPL. OpenEar uses the rtlsdr project, which is GPL. Therefore OpenEar needs to be GPL also, and as such, the source must be distributed as well. https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL

**Comment by moneriomaa** [comment]
note that you talk about RTL2832U chipset that used on so many hardware
dont worry i remove rtlsdr dll dependent and replaced it by driver of this RTL2832U
driving rtl2832U is so easy thing and is not good reason for me that for using so easy part of driving upload my complicated codes that use my time so years

**Comment by moneriomaa** [comment]
i changed your issue title from "GPL violation unless source code is released" to "i need OpenEar source code" please speak clear not behind wall
