### ISSUE TITLE
Wonte run windows 10

### ISSUE THREAD

**Issue by kevtheskin** [moneriomaa/openear#11]
Hi there cant get this to run on my windows 10 pro box. It first looks for 
---------------------------
OpenEar.exe - System Error
---------------------------
The code execution cannot proceed because rtlsdr.dll was not found. Reinstalling the program may fix this problem. 
I copied file from sdr# but now another error.
---------------------------
OpenEar.exe - Application Error
---------------------------
The application was unable to start correctly (0xc000007b). Click OK to close the application. 
 I hope you can help me fix this. Looks good cheers 73s Kev

**Comment by moneriomaa** [comment]
Hi this error " (0xc000007b)" about not suitable x86 , x64 dll placement
probably you placed x86 rtlsdr.dll in x64 openear.exe folder
you must download rtlsdr.dll x64 version
probably your sdrsharp is x86 version with rtlsdr.dll for x86

**Comment by kevtheskin** [comment]
Where can I get the rtlsdr.64 please

**Comment by moneriomaa** [comment]
you can find both x86 and x64 on
https://ftp.osmocom.org/binaries/windows/rtl-sdr/
