### ISSUE TITLE
Tetra No Sync

### ISSUE THREAD

**Issue by GrafvonBerg** [moneriomaa/openear#12]
Hey :)

When i click on Tetra and go to 390.000MHZ the Tool says: No Sync
What does that mean?

regards

**Comment by moneriomaa** [comment]
it mean that probably you did not read Note part that i said :)
-fix issue for clicking center of spectrum (some ddc simple problems) currently you can’t receive signal on center of main spectrum you must shift signal 100KHz or more from center to right or left then you get clear output, as i show it on my sample picture,(for ADS-B there is no problem here, cause there is no ddc) this is known issue and i solve in next releases

it is temporarily solution before i fix this issue
but if stay "not sync" feedback me

**Comment by GrafvonBerg** [comment]
ah okay ;) Thanks for the Answer. I tested it but it stay at No sync... so i will wait, no problem :)

**Comment by moneriomaa** [comment]
you're welcome
ok if you placed tetra signal right or left side of center of spectrum then you must see Sync
if it shows you no sync, you must look at constellation  gragh,
do you see 8 point clearly? this point must be 4|4 it means that 4 point on right of middle and 4 point must be on left of middle on constellation graph  
if you see 3|3 and 2 point on top and button it is meant that center is not correct
or if you see graph like loop with moving point it is meant that this is Tetra2 QAM 
witch state of above said you see on constellation graph? 
also you can take screenshot from program and send it to me by mail that i noted on button of readme file, with see image of your program i can guess cause of "No sync" easier

**Comment by GrafvonBerg** [comment]
Okay, i sent you an email

**Comment by moneriomaa** [comment]
description for readers:
ok, i checked email and see that is about known center issue, 
i described on e-mail for temporarily shift signal to right or left
this is not solution for issue but can decode signal without problem
