### ISSUE TITLE
POCSAG Not decoding

### ISSUE THREAD

**Issue by catalinalb** [moneriomaa/openear#14]
Hi there,

I have the latest version v1.5.4 I am tuned to 466.075 In Germany, I see the signal but nothing in the decoding frame. 

Any ideas?
Thank you

**Comment by GrafvonBerg** [comment]
Guckst du bei Tetra oder DMR? Bei Tetra gibt's nen kleines Problem das er nicht genau die Frequenz nimmt, verschiebst du den Regler etwas klappt es

**Comment by moneriomaa** [comment]
Hello
they are two notes
note 1:
as i said on[ Note part ](https://github.com/moneriomaa/openear#note) of Github readme 
this is known issue thay i try to solve it but before i solve this you try below temporary solution
-fix issue for clicking center of spectrum (some ddc simple problems) currently you can’t receive signal on center of main spectrum you must shift signal 50 or 100KHz or more from center to right or left then you get clear output, as i show it on my sample picture,(for ADS-B there is no problem here, cause there is no ddc) this is known issue and i solve in next releases
it is temporarily solution before i fix this issue

note 2:
for dmr and tetra there is now carrier recovery then you must click center of signal you can check this by red color of signal must be cover all signal and then you can get sync and voice traffic
another way for check correct center of tetra is that you must see 8 point in constellation by 4|4 arrangement it is correct and arrangement like 3|3 and one up and one down is not correct.
(at first check note 1 and then note 2 is valid)

**Comment by catalinalb** [comment]
Thank you for your reply. 
You are doing a wonderful job! 

Bye!

**Comment by moneriomaa** [comment]
you're welcome :)
Thanks
