### ISSUE TITLE
Added in next update ! 

### ISSUE THREAD

**Issue by khanfar** [moneriomaa/openear#18]
thanks moneriomaa for your great work , i would like to put lists of target in future to add  : 

1- add WFM for listening to broadcast frequencies . 
2- add squelch button with level , its very important when listening to NFN analog radios .  
3- add scan capability in same rtl dongle bandwidth like 2.4 , so you can scan analog NFM in spectrum.
4- add save frequency button so you can go it when you need it .
5- add like 3 save VFOs button for analog NFM radios . (important for analog scan)
6- add night mode GUI , its useful to use in night or in car with tablet 
7- add menu up to chose many options you add !
8- add capability to stream voice in LAN in web browser view or vlc 

i wish some of these seen in next version soon ....
thanks alot for your amazing project....

**Comment by moneriomaa** [comment]
you're welcome
Thanks for you suggestion
yes, there is many options can be added for more improving for software, can be driven from most used GUI like SDRsharp or HDSDR or ... or like OpenEar Pro! ;)
this improvement will be happened on Pro version with some extra protocol features
also some of them is minimum requirement of SDR GUI but  all of them planed for Pro version
thanks for comment and suggestions again

**Comment by khanfar** [comment]
thanks , are you working on pro version ? or expected time for release ?

**Comment by moneriomaa** [comment]
you're welcome
Pro version GUI is ready but like Skin with simple am/fm demodulator!
in this phase more focused on implementing and adding more protocols to current simple OpenEar
after number of protocols reached to 10 or 15 then That's when i need to work on completing Pro version and i start adding protocols to it (this is not hard work and could be done in a month)
but currently i have no plan for Pro version release date,  cause focus is on adding protocols

**Comment by khanfar** [comment]
thanks ...
