### ISSUE TITLE
(Question) How are timeslots and DMO handled?

### ISSUE THREAD

**Issue by bierviltje** [moneriomaa/openear#2]
Question: is there also DMO support?

How is activity on multiple time slots at once handled? On busy carriers all 4 slots are used at the same time.

Is there a way to show information such as MCC, MNC, etc?

**Comment by moneriomaa** [comment]
1-about DMO support: answer is no
2-for multiple slots, currently last call-id selected and send to vocoder but coz code is objective in future 4 vocoder path is replaced and can listen to all 4 slot voice.
3-for MCC and MNC currently you can check the "save output" and software save the logs that contains those parameters but if you like that realtime show on GUI, ok i do that with another features like call list may be in few days.
