### ISSUE TITLE
please add WFM Support

### ISSUE THREAD

**Issue by khanfar** [moneriomaa/openear#21]
hello ,, thanks for your software ,,, Please add this feature as soon as possible ! i thinks its no need alot of time to do it . let us enjoy listen to local fm station ! make it support for WFM , thanks .

**Comment by moneriomaa** [comment]
Hello
You're welcome
in fact the problem is not on WFM, it is about DDC problem that if signal is wider the problem shows bigger
but i try to solve center ddc problem as soon as possible for enabling WFM (it is added but disabled and hidden for issue that i said)

**Comment by khanfar** [comment]
thanks moneriomaa  , hope fix this soon , i see the software looks like STANAG-4285 , i see it in blogspot in internet http://i56578-swl.blogspot.com/2014/05/8ary-psk.html 

if the same developer , hope to add stanag settings , bitrate .... , and customize keyboard ... TETRA , ACARS , AIS , mpt1327 , ... thanks

**Comment by moneriomaa** [comment]
"if the same developer , hope to add stanag settings , bitrate .... , and customize keyboard ... TETRA , ACARS , AIS , mpt1327 , ... thanks"
some confusing! but i am not "tony.anselmi" :D i saw his name on top of this link
about stanag-4285 i think more that 98% of traffic is encrypted and maybe with
spending time with few output!
i try to spend time for more output
but in future maybe try for 4285

**Comment by moneriomaa** [comment]
many protocols can be added to software but with priority of public usage

**Comment by khanfar** [comment]
👍 thanks... I see the first priority make its works well with WFM , and get the button appear in GUI ,,, it will make this amazing software go to public and many users enjoying this software ... the WFM very important in any software defined radio released ! Thanks .

**Comment by moneriomaa** [comment]
👍
