### ISSUE TITLE
Maybe a bug.

### ISSUE THREAD

**Issue by Crypto74** [moneriomaa/openear#26]
When I start Openear I get this message. "The program cannot start correctly (0x000007b). Click ok to close the program. " Maybe I need to install something. ?

Windows 10 Pro
Version 1909
Build     18363.900

**Comment by moneriomaa** [comment]
it is about rtlsdr.dll and program x86 or x64 version
if you run 64 bit version you must copy rtlsdr.dll x64
and if you run 32 bit version you must copy rtlsd.dll x86
