### ISSUE TITLE
Linux, macOS ?

### ISSUE THREAD

**Issue by ah1102** [moneriomaa/openear#3]
Why is your application only for Windows in 2020? You can write in Windows and in Microsoft VC, but make the application multi-platform.

**Comment by moneriomaa** [comment]
Hello 
In 2020, there is no force to anyone to write code on specific platform (a combination of joke and serious)
software has three part of codding
- protocol modules : C++
- agents, threads and queues, ...  (data streaming and path) : VC++
- UI : vc++
there is no limitation for using modules of protocols in any paltfom coz i use c++  (with simple oprations of + - * /  :D)
but about architecture and UI vc++ used then it can run on windows
main reason of selecting vc++ is my experience in programming with vc++

**Comment by ah1102** [comment]
You need to write a universal one with the ability to build from source on any platform. Here is an example of a universal application written in vc ++ https://github.com/XRay3D/GERBER_X2 So far I have not been able to build the program due to some errors, but the main thing is to do it.
