### ISSUE TITLE
source code for linux compiling

### ISSUE THREAD

**Issue by 5l1v3r1** [moneriomaa/openear#32]
can you please share the source code as weel so we can compile it for linux

**Comment by moneriomaa** [comment]
sorry, currently it is not possible for me, some part of codes like Spectrum and waterfall and internal procedure has copy right and can't share their codes, but if i change those parts on future i can share it, but currently it is not on my plan

**Comment by 5l1v3r1** [comment]
Well that's fair enough i understand but at least can you please add hackrf support ?

**Comment by moneriomaa** [comment]
thanks
multi-hardware support under development and i try to add this on next major update
