### ISSUE TITLE
sdr openera  

### ISSUE THREAD

**Issue by gaspar1987** [moneriomaa/openear#4]
'd like to.
Good evening.
I would like you to make software with a water fountain to see the tapes and trams.
What we see on digital.
Because it doesn't work in.
Tmo.

**Comment by moneriomaa** [comment]
Hello
you;re welcome
sorry, i can't understand your meant exactly, because English is not my
first language
can you describe your meant more?
thanks

**Comment by moneriomaa** [comment]
did you mean that i use waterfall on UI?

**Comment by gaspar1987** [comment]
![image](https://user-images.githubusercontent.com/13591469/76993064-923b1d00-694c-11ea-89e6-d89d330365d7.png)
bonjourIl marche super, bien.
Et merci beaucoup.
Pas plus.

**Comment by gaspar1987** [comment]
modulation  wfm  DMR  ETC.

**Comment by moneriomaa** [comment]
you're welcome
in last version i added DMR but temporarily i disabled tetra option for improving performance.
for WFM small bug here for center of spectrum that is about DDC module that i try to solve this
this bug cause to wide band modulation do not work correctly.
i add waterfall in next version

**Comment by gaspar1987** [comment]
Bonjour, le fameux dévers que vous avez fabriqué.
Je vous avais fabriqué est super bien. J’ ai pu écouter du numérique est normal classique, le son est fort.
Puis.
Il faudrait mettre  DECODE de la cryptoaudio 256 AES  .

Il sera super bien.

Bonne journée.

**Comment by moneriomaa** [comment]
you're welcome
about 256 AES >>>OMG :)
it is maybe final part of work about DMR
currently i work on BP, in theory BP decryption is easy but finding signal from different manufactures and process them is a hard part of work
Bonne journée.

**Comment by gaspar1987** [comment]
Good morning, sir.
I used your device. Who is a very specific software? Very perfume. Okay, and it's the perfect sound. Ideal, because I have an amplifier that allows him to use it through help. Long distances. I listened to DS D tetras. Seas of the.
Aviation and so on, but I wanted to tell you that you have to put.
Stop the.

**Comment by gaspar1987** [comment]
I'd like you to use it.
A system for listening to trams.
Who uses a data good?
Specific,FMS DECODE

**Comment by moneriomaa** [comment]
Hello thanks
sorry, I did not understand the end of your text
Maybe you'd better write French and I'll translate it and reply to you
thanks

**Comment by gaspar1987** [comment]
bonsoir  monsieur je veux du acras décode + tetrapol  +p25 1 et 2 decode  pour bon logiciel qui enregistrent le disque  et compatible Norton . super

**Comment by moneriomaa** [comment]
bonsoir monsieur
about Acars it is Ready, i add it(in 3 month)
about tetrapol i can't reach good vocoder but try again
about p25 phase1 ok it is in plan(in 6 month), but phase2 i must research

about "pour bon logiciel qui enregistrent le disque" if you meant recording voice on disk yes on future i add this

about " compatible Norton" maybe some description is needed!

Regards
