### ISSUE TITLE
Moi, je voulais. Savoir si vous pouvez améliorer? Votre SDR.

### ISSUE THREAD

**Issue by gaspar1987** [moneriomaa/openear#44]
Bonjour monsieur je veux que vous mettre le mobiltex puis DPMR et acras etc

**Comment by moneriomaa** [comment]
dpmr,NXDN48/96 added and under test
Audio input / recording voice added under test
it will be released in next month

**Comment by gaspar1987** [comment]
Avant que vous commencez ce logiciel j'ai bien aimé le spectrale de la radio Tetra je sais que vous êtes basée en Belgique et que vous fabriquez des logiciels qui sont professionnels et bien adaptés j'aime bien et je peux écouter tout ce que je veux dans le numérique .

**Comment by gaspar1987** [comment]
Bonjour monsieur je voulais vous féliciter que votre logiciel est et que ça marche super bien si vous pouvez encore mettre plus de normes encore sur votre logiciel et le mettre comme logiciel enregistré sur un disque dur ça pourrait marcher comme des SDR Angel ou exetera sharp qui s'enregistre sur le disque dur c'est ce qu'il faut faire pour que l'antivirus autorise un logiciel voilà.

**Comment by gaspar1987** [comment]
bonjour je suis à patients d'avoir le nouveau logiciel que vous êtes en train de fabriquer ça se trouve en développeur web c'est pour cela que je test vos logiciels sont bien de DSD j'ai pu rester des choses qu'on aurait pas à avoir avec du matériel des SDR et c'est super bien j'ai réussi à écouter du Tetra du DMR du PMR exetera.
