### ISSUE TITLE
OpenEar start camera? Why?

### ISSUE THREAD

**Issue by openEarCamera** [moneriomaa/openear#46]
When start OpenEar me camera is On, and when I stop it Camera is Off.
Why?
![Open Ear Camera On](https://user-images.githubusercontent.com/69427439/89735359-b4a01500-da6a-11ea-97d8-e7a9db55f42b.png)
![Open Ear Camera Off](https://user-images.githubusercontent.com/69427439/89735360-b538ab80-da6a-11ea-92c2-6ecd2546517c.png)

**Comment by moneriomaa** [comment]
there is no line in openear code, related to using camera, 
you can check on windows 10 which programs used camera
settings>privacy>camera you can run openear and see if it listed or not! (for me not)
for my curiosity i run openear and see no camera using detected!
