### ISSUE TITLE
Error on startup - SOLVED

### ISSUE THREAD

**Issue by IZ7QEB** [moneriomaa/openear#48]
I downloaded the last 1.6 version on my W10 64bit and it don't work! 
I added the rtlsdr.dll and msvcr120.dll library .. Installed also Visual C++ distribution... But nothing!
Any solution? 
Attachments the screen of the error.
Thank you. 

![openera64](https://user-images.githubusercontent.com/9398445/91178381-566b6700-e6e5-11ea-95a6-4e851702e4db.png)

**Comment by elfronto** [comment]
Hi. The same problem for me since v1.6.
Have a nice day.

**Comment by moneriomaa** [comment]
this error is about using x86 rtlsdr dll be side of x64 openear.exe
use x64 version of rtlsdr.dll

**Comment by IZ7QEB** [comment]
I tried to copy the rtlsdr.dll file from sdr software (that work) into the openear folder and don't work. Ok, it maybe x86.
Where can I found the .dll x64  ?? tnx

**Comment by westhead74** [comment]
I can't get the x64 version of 1.7.0 working on Windows 10 and I have installed the x64 rtlsdr dll.

**Comment by moneriomaa** [comment]
> I can't get the x64 version of 1.7.0 working on Windows 10 and I have installed the x64 rtlsdr dll.

please describe more about your problem, error or message when you try for run or other info

**Comment by IZ7QEB** [comment]
Solved! The rtlsdr.dll 32bit and 64bit versions can be founded at this link: 
https://www.rtl-sdr.com/manual-installation-of-sdr/  .. following the manual setup. You can extract the RTLSDR.DLL (your version) and drop it in the Openear folder.  It work!  In my case, the 64bit version is ok.
