### ISSUE TITLE
msvcr120d.dll was bot found

### ISSUE THREAD

**Issue by seraj94ai** [moneriomaa/openear#5]
I downloaded the missing missing msvcr120d.dll file , but I got new problem ! 
![image](https://user-images.githubusercontent.com/42117360/76569630-4277d400-64bc-11ea-977f-3b13b0e0f465.png)

**Comment by moneriomaa** [comment]
are download write x64 version of dll?
tell me size of dll please

**Comment by seraj94ai** [comment]
![image](https://user-images.githubusercontent.com/42117360/76571271-c1bad700-64bf-11ea-8754-90ed9b7216d6.png)

**Comment by moneriomaa** [comment]
did you install Visual C++ Redistributable Package that i mentioned on readme file?
this error you said maybe have some reson but in this case 
"Uninstall and then reinstall the Microsoft Visual C++ Redistributable" maybe is solution.

**Comment by moneriomaa** [comment]
i compiled it with static link library, download again openear and try to run

**Comment by moneriomaa** [comment]
If you still have this problem
As I understood this error can have many causes
For example:
-Your operating system should be x64 for this software
-check compatibility option on properties
-run as administrator
and some other solutions that you can easyly find on youtube by searching this error
