### ISSUE TITLE
TETRA Trunk Tracking

### ISSUE THREAD

**Issue by grahampaull** [moneriomaa/openear#53]
The ability to follow calls on TETRA TMO sites.

**Comment by moneriomaa** [comment]
can you describe more about this?
is this about improving current listening procedure? 
 currently last call id selected for listening, for example when user is listening on call id:n and call id:n+1 is coming, then software voice out the call id:n+1
is your request about ability to continue current call id listening by user select?

**Comment by grahampaull** [comment]
Hi, Sorry I should have put more detail in.

Basically how this works : https://forums.radioreference.com/threads/tetra-demodulator-trunk-tracking-demonstration.370639/
