### ISSUE TITLE
NO RTL device found.

### ISSUE THREAD

**Issue by goldyka** [moneriomaa/openear#6]
Hi,

Great job and thank you for it. Can't wait to try it out, but after installing the missing DLL's i connect my Hackrf and it tells me, NO RTL device found. HDSDR and SDRconsole both can find it and use it.

Any help would be perfect because we are in curfew and id really like to kill some time.

**Comment by moneriomaa** [comment]
Hi
thanks for you attention, unfortunately currently software only supports
RTL devices (that use rtl2832u chip-set )
HackRf is not rtl device, HDSDR and SDRconsole as i know is program for
spectrum view and simple analog demodulation  with nice GUI
there is no limitation for hardware support by OpenEar but i have not
HackRf hardware for adding it to my program and test it
in future i try to find Hackrf c++ lib to add to my program

Best Regards
