### ISSUE TITLE
Tetra just shows SYNC

### ISSUE THREAD

**Issue by chimera234** [moneriomaa/openear#61]
Hello,

When centering to a Tetra frequency I just see SYNC, no audio.
What does this mean?

Thanks
Chimera

![sync](https://user-images.githubusercontent.com/25669732/95027647-7efa5f80-069a-11eb-8311-1a18ba0cb3e5.png)

**Comment by moneriomaa** [comment]
Hello
only sync means that channel does not contains voice traffic on that time

**Comment by chimera234** [comment]
Thanks for clarification!
Another question, on some Tetra channels I don’t get SYNC. What does this mean?

Thanks
Chimera

**Comment by westhead74** [comment]
You might not have a strong enough signal/transmission if you there's no sync.

**Comment by moneriomaa** [comment]
if power of is your signal is good then prevent from placing signal on center of spectrum(it is old issue about dc value of center of spectrum, i think it is solved by dc remover but for test it is better that place signal out of center of spectrum) and  try to click more accurate on center of signal
if all above done and also you can not get sync maybe it is tetra2 or TETRA Enhanced Data Service (TEDS) that use QAM modulation and it is not decoded by tetra decoder on openear

**Comment by chimera234** [comment]
All clear! Many thanks for clarification
