### ISSUE TITLE
invitation for DMR Basic privacy

### ISSUE THREAD

**Issue by moneriomaa** [moneriomaa/openear#8]
Hi
i try to add basic encryption fetures to sofware in two modes 1-with a key and 2-without key
for this reason
I invite people with dmr hardware to announce that if they are interested I can develop and test the software with them
thanks

**Comment by onmia** [comment]
i have some dmr equipment , i can help test the basic encryption features.

**Comment by moneriomaa** [comment]
so good, currently basic encryption phase under development, and usable version is not friendly and straight using version (it means that code must run under Visual studio IDE and run-time debugging and changing)
but if you can gathering some recorded I/Q data for testing under this condition for me, this is so useful
for this you should know your basic privacy base key that using when you create traffic.
(10 or 16 or 40 bits base-key, dependent on manufacture of DMR hardware, it could set by DMR programmer software)
and  record signal by SDRsharp baseband when you send me used base key and recorded signal,
by this signal i can test decryption algorithm and changing the code to reach voice signal
thanks

**Comment by bibib86** [comment]
Hi,

Do you know this ?:
https://github.com/travisgoodspeed/md380tools/issues/50
Maybe it can help you

If you need capture, give us more details ...
What a setting in SDRSharp.
What a duration of capture.
how to send the capture.

**Comment by moneriomaa** [comment]
HI
yes i check this before, decryption is under debugging and some manufactures have little different basic privacy scheme with others
about capturing details:
currently basic privacy is needed
you can record by sdrsharp baseband signal(more file size) or by raw input audio of dsdplus (with pressing r key) (smaller size) 
and if you know which key used for encryption it help for better debugging but is not necessary  
about duration from 5 seconds or up is good 
you can send it by google drive or any shareable host like wetransfer.com or sendspace.com
thanks for your help

**Comment by bibib86** [comment]
Hello,
sample send via wetransfer today.
best regards.

**Comment by moneriomaa** [comment]
Hello
thanks a lot
i sent you e-mail
Best Regards

**Comment by moneriomaa** [comment]
Hello 
Thanks a lot
i sent you e-mail
Best Regards

**Comment by onmia** [comment]
Hi ,

Hope all is well ? 

How are you getting on with your Project ? 

 

Regards,

Paul.

**Comment by moneriomaa** [comment]
> Hi , Hope all is well ? How are you getting on with your Project ? Regards, Paul.

Hi
Thanks, i hope all is well for you too
currently BP decryption is works on offline and under IDE debugging
and i have no decision for how can add this feature to OpenEar
i note that when all people can decrypt the traffic there is no Point and then BP is down!
Best Regards

**Comment by countryboy057** [comment]
Do you need any help with testing? I have plenty of DMR radios
