### ISSUE TITLE
msvcr120D.dll needed 

### ISSUE THREAD

**Issue by notwired** [moneriomaa/openear#9]
msvcr120D.dll is needed on launch and not available as this is D - debug version compiled. Please compile for release. Thank you.

**Comment by moneriomaa** [comment]
program compiled on release on static link library some times this error usually about something missing in your system
this [link ](https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system) on Microsoft and maybe help you

**Comment by notwired** [comment]
msvcr120.dll si the normal one and is present on my system
msvcr120D.dll is the debug version usuallyw not found

**Comment by moneriomaa** [comment]
did you download last version?
i uploaded only 2th and 3th commit with debug compiling
others compiled in release mode and replaced

**Comment by moneriomaa** [comment]
I think i found the problem 
it is about SourceDLL.dll i check and find it i complied it on Debug 
but exe is in release and MSVCR120D needs for SourceDLL.dll
i correct it in next commit in next few days

**Comment by moneriomaa** [comment]
i uploaded release version of DLLs 
please check msvcr dll missing problem and send feedback
thanks

**Comment by notwired** [comment]
Working good ! Thank you !

**Comment by moneriomaa** [comment]
You're welcome
